apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: install-openshift-gitops
policyDefaults:
  namespace: policies
  placement:
  clusterSelector:
      matchExpressions:
      - key: environment
        operator: In
        values:
        - prod
        - qa
  remediationAction: enforce
policies:
  - name: openshift-gitops-installed
    manifests:
      - path: openshift-gitops-subscription.yaml
    
